### ISSUE TITLE
Can't Search Outgoing Emails

### ISSUE THREAD

**Issue by digisavvy** [ZilongXue/claude-post#1]
Claude Post seems unable to search outgoing emails

```
search-emails
parameters: 
  keyword: [someone@example.com]
Result: Error about end_date_obj variable
```
and
```
search-emails
parameters:
  keyword: [someone@example.com]
  start_date: 2025-01-07
  end_date: 2025-01-07
Result: No emails found
```

**The function requires date parameters despite them being marked as optional in the schema**
No apparent way to filter for outgoing mail specifically
All results show only incoming mail regardless of search parameters
The 'From' field in results only shows external senders, suggesting outgoing mail isn't indexed in the searchable database

**The schema shows these parameters:**
keyword (optional string)
start_date (optional string in YYYY-MM-DD format)
end_date (optional string in YYYY-MM-DD format)
